Repository sandialabs/OpenCSP, pull requests merged in 2025-01, with the labels that each got.

#172 creating TestMotionBasedCanting
  opencsp/common/lib/csp/Facet.py
  opencsp/common/lib/csp/HeliostatAbstract.py
  opencsp/common/lib/csp/Tower.py
  opencsp/common/lib/render_control/RenderControlFacet.py
  opencsp/common/lib/render_control/RenderControlFacetEnsemble.py
  opencsp/common/lib/render_control/RenderControlTower.py
  opencsp/common/lib/test/TstMotionBasedCanting.py
  opencsp/common/lib/test/data/input/TestTowerOutput/tto001_Single_Tower_3d.png
  opencsp/common/lib/test/data/input/TestTowerOutput/tto002_Multiple_Towers_3d.png
Labels: enhancement

#194 Fix test_with_attrfile bug and re-enable test
  opencsp/common/lib/file/AttributesManager.py
  opencsp/common/lib/render/ImageAttributeParser.py
  opencsp/common/lib/render/test/test_ImageAttributeParser.py
  opencsp/common/lib/tool/file_tools.py
Labels: bug

#201 Restrict scipy version, <= 1.14.1
  requirements.txt
Labels: bug

#199 Document opencsp/app/select_image_points
  doc/source/library_reference/app/select_image_points/config.rst
  doc/source/library_reference/app/select_image_points/index.rst
  doc/source/library_reference/index.rst
Labels: documentation

#197 common/lib/deflectometry: Test docs
  opencsp/common/lib/deflectometry/ParamsSlopeSolver.py
  opencsp/common/lib/deflectometry/Surface2DParabolic.py
  opencsp/common/lib/deflectometry/Surface2DPlano.py
  opencsp/common/lib/deflectometry/slope_fitting_2d.py
Labels: documentation
